Doms maintenance update
statsbiblioteket/larm-doms-exporter pull request #2
Opened 2020-07-28 14:10 UTC by kb-Alexander

Main Changes: 
 * Update java version (1.8 -> 11)
  * Comply with forbidden api
  * Update junit (4 -> 5), with corresponding changes to tests
  * Update most external dependencies

2020-07-29 10:33 UTC, HalinaHolst commented on src/main/java/dk/statsbiblioteket/larm_doms_exporter/persistence/dao/DomsExportRecordDAO.java
> +       List<DomsExportRecord> records = getSession().createQuery("FROM DomsExportRecord WHERE state = ?0 ORDER BY lastDomsTimestamp DESC ").setParameter(0, ExportStateEnum.COMPLETE).list();
state = ?0 - er det en ny syntaks, kan se det samme længere nede? Hvad betyder det?

2020-07-31 09:52 UTC, kb-Alexander commented on src/main/java/dk/statsbiblioteket/larm_doms_exporter/persistence/dao/DomsExportRecordDAO.java
> +       List<DomsExportRecord> records = getSession().createQuery("FROM DomsExportRecord WHERE state = ?0 ORDER BY lastDomsTimestamp DESC ").setParameter(0, ExportStateEnum.COMPLETE).list();
Det skulle meget gerne betyde det samme, "?" er blevet legacy syntax og vi får kastet en "java.lang.IllegalArgumentException: org.hibernate.QueryException: Legacy-style query parameters (`?`) are no longer supported; use JPA-style ordinal parameters (e.g., `?1`) instead"

2021-04-22 12:01 UTC, kingudk requested changes

2021-04-22 12:01 UTC, kingudk commented on pom.xml
> +            <version>1.2.17</version>
There should only be one log implemtation used (logback should be preffered)

2021-04-22 12:01 UTC, kingudk commented on pom.xml
> +            <version>9.2-1002.jdbc4</version>
Postgresql driver should updated to a much newer version. Try to see if 
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.2.19</version>
</dependency>
works as expected

2021-04-22 12:01 UTC, kingudk commented on src/main/java/dk/statsbiblioteket/larm_doms_exporter/consumer/processors/DoExportProcessor.java
> +            os.write(result.getBytes("utf-8"));
Consider using StandardsCharset.UTF8.name()

2021-04-22 12:01 UTC, kingudk commented on pom.xml
> +            <version>5.6.2</version>
Time flies and junit can be updated to 5.7.1 :)

2021-04-22 12:01 UTC, kingudk commented on Jenkinsfile
> +            inheritFrom: 'kb-jenkins-agent-java-11',
Should be changed to: "inheritFrom: 'maven'," as we now use the standard maven agent image.

2021-04-22 12:01 UTC, kingudk commented on pom.xml
> +            <version>1.7.9</version>
should be 1.7.30 instead

2021-04-23 06:21 UTC, kb-Alexander commented on pom.xml
> +            <version>5.6.2</version>
When I update junit, the tests fail to run (0 tests get run)

2021-04-23 11:27 UTC, kingudk commented on pom.xml
> +            <version>5.6.2</version>
fixed by updating parentpom

2021-04-23 12:51 UTC, kingudk approved these changes

2021-04-23 12:52 UTC, merged